# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"?\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06system\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t28\n\x0cLoginService\x12(\n\x05login\x12\r.LoginRequest\x1a\x0e.LoginResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=14
  _globals['_LOGINREQUEST']._serialized_end=64
  _globals['_LOGINRESPONSE']._serialized_start=66
  _globals['_LOGINRESPONSE']._serialized_end=129
  _globals['_LOGINSERVICE']._serialized_start=131
  _globals['_LOGINSERVICE']._serialized_end=187
# @@protoc_insertion_point(module_scope)
